os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_install:
  - env | sort
  - export home=$(pwd)
  - export travis_dir="${home}/images/${VERSION}/${VARIANT}"
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME="docker-covid:${TAG}"

install:
  - echo "Changing to travis test directory ($travis_dir)"
  - cd "$travis_dir"
  # Test container build
  #- docker build 
  #  --build-arg TAG=${TAG}
  #  --build-arg VCS_REF=${VCS_REF}
  #  --build-arg BUILD_DATE=${BUILD_DATE}
  #  -t $IMAGE_NAME .
  - sed -i -e "s|#image: .*|#image: ${IMAGE_NAME}|g" docker-compose.test.yml
  - docker-compose -f docker-compose.test.yml build

before_script:
  - docker images

script:
  - echo "Changing to travis test directory ($travis_dir)"
  - cd "$travis_dir"
  # Test containers run
  - travis_retry docker-compose -f docker-compose.test.yml up -d && sleep 60
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "covid-db"
  - docker-compose -f docker-compose.test.yml ps "covid-db" | grep "Up"
  - docker-compose -f docker-compose.test.yml logs "covid"
  - docker-compose -f docker-compose.test.yml ps "covid" | grep "Up"
  - echo 'Wait until containers init and tests are over' && sleep 120
  - docker-compose -f docker-compose.test.yml logs "sut"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"
  # Test containers can be dropped and restarted
  - docker-compose -f docker-compose.test.yml down
  - travis_retry docker-compose -f docker-compose.test.yml up -d && sleep 60
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "covid-db"
  - docker-compose -f docker-compose.test.yml ps "covid-db" | grep "Up"
  - docker-compose -f docker-compose.test.yml logs "covid"
  - docker-compose -f docker-compose.test.yml ps "covid" | grep "Up"
  - echo 'Wait until containers init and tests are over' && sleep 120
  - docker-compose -f docker-compose.test.yml logs "sut"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"
  # Test the NGinx reverse proxy config
  - docker-compose -f docker-compose.test.yml down
  - echo "Changing to home directory ($travis_dir)"
  - cd "$home"
  - sed -i -e "s| monogramm/docker-covid:.*| ${IMAGE_NAME}|g" docker-compose.yml
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs

notifications:
  email: false

env: # Environments
    - VERSION=master VARIANT=alpine
    - VERSION=master VARIANT=debian
