version: "2"

volumes:
  covid_var:
  covid_log:
  covid_tmp:
  covid_db:
  covid_rd:

services:
  covid:
    # For production, download prebuilt image
    image: ${COVID_IMAGE}
    container_name: covid
    #restart: always
    depends_on:
      - covid-db
    links:
      - covid-db
    expose:
      - 3000
    volumes:
      - covid_var:/covid/var
      - covid_log:/covid/log
      - covid_tmp:/covid/tmp
      # If you want locally mounted volumes
      #- ${COVID_HOME}/var:/covid/var
      #- ${COVID_HOME}/log:/covid/log
      #- ${COVID_HOME}/tmp:/covid/tmp
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://${COVID_DB_USER}:${COVID_DB_PASSWD}@covid-db:5432/${COVID_DB_NAME}?timeout=5000&reconnect=true
      - SECRET_KEY_BASE=${COVID_SECRET}
      # Twilio's API to send SMS
      - TWILIO_ACCOUNT_ID=${COVID_TWILIO_ACCOUNT_ID}
      - TWILIO_AUTH_TOKEN=${COVID_TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${COVID_TWILIO_PHONE_NUMBER} 
      # Slack/Mattermost to monitor failed SMS
      - SLACK_HOOK_URL=${COVID_SLACK_HOOK_URL}
      # Redis Config
      - REDIS_HOST=covid-redis
      - REDIS_PORT_NUMBER=6379
      #- REDIS_PASSWORD=${COVID_REDIS_PASSWD}

  covid-db:
    image: postgres:10.4-alpine
    container_name: covid-db
    restart: always
    #ports:
    #  - 5432:5432
    volumes:
      - covid_db:/var/lib/postgresql/data
      # If you want locally mounted volumes
      #- ${COVID_HOME}/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_DB=${COVID_DB_NAME}
      - POSTGRES_USER=${COVID_DB_USER}
      - POSTGRES_PASSWORD=${COVID_DB_PASSWD}

  covid-redis:
    image: redis:5.0
    container_name: covid-redis
    restart: always
    #healthcheck:
    #  test: ["CMD", "redis-cli", "ping"]
    volumes:
      - covid_rd/:/data
      # If you want locally mounted volumes
      #- ${COVID_HOME}/redis/:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      #- REDIS_PASSWORD=${COVID_REDIS_PASSWD}
      - ALLOW_EMPTY_PASSWORD=yes
